# Generated by Django 4.2.3 on 2023-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='activity_pics/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='partner_pics/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
