# Generated by Django 4.2.3 on 2023-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_activity_description_activity_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
