# Generated by Django 4.2.3 on 2023-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_activity_picture_alter_partner_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='activity_pics/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='partner_pics/'),
        ),
    ]
